input_data_path: "data/raw/train.csv"
downloading_params:
  google_drive_url: "https://drive.google.com/uc?id=1UfkLKJno3m1Hzk8mxlx4oQ9oXlgZj7qR"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  target_col: "condition"