data:
  input_data_path: "data/raw/data.csv"
  downloading_data_params:
    download_data: False
    google_drive_url: "https://drive.google.com/uc?id=1UfkLKJno3m1Hzk8mxlx4oQ9oXlgZj7qR"
  splitting_params:
    test_size: 0.2
    random_state: 42 
  
preproc:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"

model:
  output_model_path: "models/model_rf.pkl"
  metric_path: "models/metrics_rf.json"
  model_type: "RandomForestClassifier"
  rf_params:
    n_estimators: 300
    max_depth: 6
    random_state: 42
  