name: Python application

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lints
      run: |
        # flake8
        flake8 ml_app
        # start pylint
        python lints/start_pylint.py
    - name: Test with unittest
      run: coverage run ml_app/tests/test.py
    - name: Tests report
      run: coverage report
